// GENERATED by tools/extract_game_tables.py - do not edit by hand.
//
// The game's own names for its command numbers, its pattern numbers, its MoveCode bits and
// its built-in palettes, out of the unpacked data files. Names and numbers only; see the
// tool for why that line is where it is.

#include "Game/GameTables.h"

#include <cstddef>

namespace {

struct Named { unsigned value; const char* name; };

const Named kCommands[] = {
	{ 50u, "Skill_DyingIWE" },
	{ 60u, "Liberate" },
	{ 61u, "Blast" },
	{ 62u, "ComboBlast" },
	{ 63u, "BoundBlast" },
	{ 70u, "Skill_IWEXIST" },
	{ 80u, "Dash_F_Douji" },
	{ 81u, "Dash_B_Douji" },
	{ 90u, "Skill_236236EX" },
	{ 91u, "Skill_214236EX" },
	{ 92u, "Skill_214214EX" },
	{ 100u, "Skill_DoubleCircleEX" },
	{ 101u, "Skill_DoubleCircleC" },
	{ 102u, "Skill_DoubleCircleB" },
	{ 103u, "Skill_DoubleCircleA" },
	{ 110u, "Skill_CircleEX" },
	{ 111u, "Skill_CircleC" },
	{ 112u, "Skill_CircleB" },
	{ 113u, "Skill_CircleA" },
	{ 116u, "Skill_41236SP_ABC" },
	{ 119u, "Skill_41236EX" },
	{ 120u, "Skill_41236SP" },
	{ 121u, "Skill_41236C" },
	{ 122u, "Skill_41236B" },
	{ 123u, "Skill_41236A" },
	{ 130u, "Skill_623EX" },
	{ 131u, "Skill_623C" },
	{ 132u, "Skill_623B" },
	{ 133u, "Skill_623A" },
	{ 139u, "Skill_236SP" },
	{ 140u, "Skill_236EX" },
	{ 141u, "Skill_236C" },
	{ 142u, "Skill_236B" },
	{ 143u, "Skill_236A" },
	{ 149u, "Skill_63214SP" },
	{ 150u, "Skill_63214EX" },
	{ 151u, "Skill_63214C" },
	{ 152u, "Skill_63214B" },
	{ 153u, "Skill_63214A" },
	{ 160u, "Skill_421EX" },
	{ 161u, "Skill_421C" },
	{ 162u, "Skill_421B" },
	{ 163u, "Skill_421A" },
	{ 167u, "Skill_214BC" },
	{ 170u, "Skill_214EX" },
	{ 171u, "Skill_214C" },
	{ 172u, "Skill_214B" },
	{ 173u, "Skill_214A" },
	{ 175u, "Skill_C0202C" },
	{ 176u, "Skill_C0202B" },
	{ 177u, "Skill_C0202A" },
	{ 178u, "Skill_020202EX" },
	{ 180u, "Skill_0202EX" },
	{ 181u, "Skill_0202C" },
	{ 182u, "Skill_0202B" },
	{ 183u, "Skill_0202A" },
	{ 184u, "Skill_0202D" },
	{ 195u, "Skill_236B_236EX" },
	{ 196u, "Skill_236B_236BorC" },
	{ 197u, "Skill_236B_236B" },
	{ 198u, "Skill_236_236" },
	{ 199u, "Skill_236_236_236" },
	{ 200u, "Skill_236_236_214" },
	{ 219u, "Skill_J41236SP" },
	{ 220u, "Skill_J41236EX" },
	{ 221u, "Skill_J41236C" },
	{ 222u, "Skill_J41236B" },
	{ 223u, "Skill_J41236A" },
	{ 230u, "Skill_J623EX" },
	{ 231u, "Skill_J623C" },
	{ 232u, "Skill_J623B" },
	{ 233u, "Skill_J623A" },
	{ 240u, "Skill_J236EX" },
	{ 241u, "Skill_J236C" },
	{ 242u, "Skill_J236B" },
	{ 243u, "Skill_J236A" },
	{ 249u, "Skill_J63214SP" },
	{ 250u, "Skill_J63214EX" },
	{ 251u, "Skill_J63214C" },
	{ 252u, "Skill_J63214B" },
	{ 253u, "Skill_J63214A" },
	{ 260u, "Skill_J421EX" },
	{ 261u, "Skill_J421C" },
	{ 262u, "Skill_J421B" },
	{ 263u, "Skill_J421A" },
	{ 270u, "Skill_J214EX" },
	{ 271u, "Skill_J214C" },
	{ 272u, "Skill_J214B" },
	{ 273u, "Skill_J214A" },
	{ 280u, "Skill_J0202EX" },
	{ 281u, "Skill_J0202C" },
	{ 282u, "Skill_J0202B" },
	{ 283u, "Skill_J0202A" },
	{ 307u, "Throw_A" },
	{ 350u, "Convert" },
	{ 351u, "Atk_DashStdBandC" },
	{ 359u, "EltBackDashCancel" },
	{ 360u, "AtkCBandC" },
	{ 361u, "AtkBandC" },
	{ 362u, "AtkJBandC" },
	{ 363u, "AtkCAandB" },
	{ 364u, "AtkAandB" },
	{ 365u, "AtkJAandB" },
	{ 368u, "Atk_DashAdd" },
	{ 370u, "Atk_DashStdC_Normal" },
	{ 371u, "Atk_DashStdB_Normal" },
	{ 380u, "Atk_DashStdC" },
	{ 381u, "Atk_DashStdB" },
	{ 390u, "Atk_DashStdC_Direct" },
	{ 391u, "Atk_DashStdB_Direct" },
	{ 397u, "Assault_Air" },
	{ 400u, "Dash_F" },
	{ 401u, "Dash_B" },
	{ 405u, "DirectSSSkill" },
	{ 410u, "Skill_AddCommand1" },
	{ 411u, "Skill_AddCommand2" },
	{ 412u, "Skill_AddCommand3" },
	{ 413u, "Skill_AddCommand4" },
	{ 414u, "Skill_AddCommand5" },
	{ 415u, "Skill_AddCommand6" },
	{ 416u, "Skill_AddCommand7" },
	{ 417u, "Skill_AddCommand8" },
	{ 418u, "Skill_AddCommand9" },
	{ 419u, "Skill_AddCommand10" },
	{ 420u, "Skill_AddCommand11" },
	{ 421u, "Skill_AddCommand12" },
	{ 422u, "Skill_AddCommand13" },
	{ 423u, "Skill_AddCommand14" },
	{ 424u, "Skill_AddCommand15" },
	{ 425u, "Skill_AddCommand16" },
	{ 426u, "Skill_AddCommand17" },
	{ 427u, "Skill_AddCommand18" },
	{ 428u, "Skill_AddCommand19" },
	{ 429u, "Skill_AddCommand20" },
	{ 430u, "Skill_AddCommand21" },
	{ 431u, "Skill_AddCommand22" },
	{ 432u, "Skill_AddCommand23" },
	{ 433u, "Skill_AddCommand24" },
	{ 434u, "Skill_AddCommand25" },
	{ 435u, "Skill_AddCommand26" },
	{ 436u, "Skill_AddCommand27" },
	{ 437u, "Skill_AddCommand28" },
	{ 438u, "Skill_AddCommand29" },
	{ 439u, "Skill_AddCommand30" },
	{ 440u, "Skill_AddCommand31" },
	{ 441u, "Skill_AddCommand32" },
	{ 442u, "Skill_AddCommand33" },
	{ 443u, "Skill_AddCommand34" },
	{ 444u, "Skill_AddCommand35" },
	{ 445u, "Skill_AddCommand36" },
	{ 446u, "Skill_AddCommand37" },
	{ 447u, "Skill_AddCommand38" },
	{ 448u, "Skill_AddCommand39" },
	{ 449u, "Skill_AddCommand40" },
	{ 450u, "Skill_AddCommand41" },
	{ 451u, "Skill_AddCommand42" },
	{ 452u, "Skill_AddCommand43" },
	{ 453u, "Skill_AddCommand44" },
	{ 454u, "Skill_AddCommand45" },
	{ 455u, "Skill_AddCommand46" },
	{ 456u, "Skill_AddCommand47" },
	{ 457u, "Skill_AddCommand48" },
	{ 458u, "Skill_AddCommand49" },
	{ 700u, "Atk1C" },
	{ 701u, "Atk1B" },
	{ 702u, "Atk1A" },
	{ 710u, "Atk2C" },
	{ 711u, "Atk2B" },
	{ 712u, "Atk2A" },
	{ 720u, "Atk3C" },
	{ 721u, "Atk3B" },
	{ 722u, "Atk3A" },
	{ 730u, "Atk4C" },
	{ 731u, "Atk4B" },
	{ 732u, "Atk4A" },
	{ 738u, "Atk4Atk_Clear" },
	{ 739u, "Atk6Atk_Clear" },
	{ 740u, "Atk6C" },
	{ 741u, "Atk6B" },
	{ 742u, "Atk6A" },
	{ 745u, "Atk6C_Add" },
	{ 746u, "Atk6B_Add" },
	{ 747u, "Atk6A_Add" },
	{ 750u, "Atk7C" },
	{ 751u, "Atk7B" },
	{ 752u, "Atk7A" },
	{ 760u, "Atk8C" },
	{ 761u, "Atk8B" },
	{ 762u, "Atk8A" },
	{ 770u, "Atk9C" },
	{ 771u, "Atk9B" },
	{ 772u, "Atk9A" },
	{ 780u, "AtkC" },
	{ 781u, "AtkB" },
	{ 782u, "AtkA" },
	{ 800u, "AtkJ1C" },
	{ 801u, "AtkJ1B" },
	{ 802u, "AtkJ1A" },
	{ 810u, "AtkJ2C" },
	{ 811u, "AtkJ2B" },
	{ 812u, "AtkJ2A" },
	{ 820u, "AtkJ3C" },
	{ 821u, "AtkJ3B" },
	{ 822u, "AtkJ3A" },
	{ 829u, "AtkJ4Atk_Clear" },
	{ 830u, "AtkJ4C" },
	{ 831u, "AtkJ4B" },
	{ 832u, "AtkJ4A" },
	{ 838u, "AtkJ6Atk_Clear" },
	{ 840u, "AtkJ6C" },
	{ 841u, "AtkJ6B" },
	{ 842u, "AtkJ6A" },
	{ 845u, "AtkJ6C_Add" },
	{ 846u, "AtkJ6B_Add" },
	{ 847u, "AtkJ6A_Add" },
	{ 850u, "AtkJ7C" },
	{ 851u, "AtkJ7B" },
	{ 852u, "AtkJ7A" },
	{ 860u, "AtkJ8C" },
	{ 861u, "AtkJ8B" },
	{ 862u, "AtkJ8A" },
	{ 870u, "AtkJ9C" },
	{ 871u, "AtkJ9B" },
	{ 872u, "AtkJ9A" },
	{ 880u, "AtkJC" },
	{ 881u, "AtkJB" },
	{ 882u, "AtkJA" },
	{ 999u, "Throw_F" },
	{ 1000u, "SmartSteer_00" },
	{ 1001u, "SmartSteer_01" },
	{ 1002u, "SmartSteer_02" },
	{ 1003u, "SmartSteer_03" },
	{ 1004u, "SmartSteer_04" },
	{ 1005u, "SmartSteer_05" },
	{ 1006u, "SmartSteer_06" },
	{ 1007u, "SmartSteer_07" },
	{ 1008u, "SmartSteer_08" },
	{ 1009u, "SmartSteer_09" },
	{ 1010u, "SmartSteer_10" },
	{ 1035u, "Barrier_Cro" },
	{ 1036u, "Barrier_Std" },
	{ 1037u, "Barrier_Air" },
	{ 1038u, "Assault_Std" },
	{ 1039u, "ForwardShift" },
	{ 1040u, "HighJump_F" },
	{ 1041u, "HighJump_N" },
	{ 1042u, "HighJump_B" },
	{ 1043u, "HighJumpCancel_F" },
	{ 1044u, "HighJumpCancel_N" },
	{ 1045u, "HighJumpCancel_B" },
	{ 1050u, "Jump_F" },
	{ 1051u, "Jump_N" },
	{ 1052u, "Jump_B" },
	{ 1053u, "JumpCancel_F" },
	{ 1054u, "JumpCancel_N" },
	{ 1055u, "JumpCancel_B" },
	{ 1060u, "MultiJump_F" },
	{ 1061u, "MultiJump_N" },
	{ 1062u, "MultiJump_B" },
	{ 1063u, "MultiJumpCancel_F" },
	{ 1064u, "MultiJumpCancel_N" },
	{ 1065u, "MultiJumpCancel_B" },
	{ 1070u, "Atk_Std6CThrow" },
	{ 1080u, "Atk_2B_2B_2B" },
	{ 1083u, "Atk_6B_6B" },
	{ 1092u, "Atk_6C_6C" },
	{ 1093u, "Atk_6C_6C_6C" },
	{ 1094u, "Atk_J6B_J6B" },
	{ 1100u, "Atk_CroC" },
	{ 1101u, "Atk_CroB" },
	{ 1102u, "Atk_CroA" },
	{ 1110u, "Atk_StdC" },
	{ 1111u, "Atk_StdB" },
	{ 1112u, "Atk_StdA" },
	{ 1120u, "Atk_AirC" },
	{ 1121u, "Atk_AirB" },
	{ 1122u, "Atk_AirA" },
	{ 1130u, "Atk_A_A" },
	{ 1131u, "Atk_B_B" },
	{ 1133u, "Atk_C_C" },
	{ 1134u, "Atk_2A_2A" },
	{ 1135u, "Atk_2B_2B" },
	{ 1136u, "Atk_2C_2C" },
	{ 1137u, "Atk_JA_JA" },
	{ 1138u, "Atk_JB_JB" },
	{ 1139u, "Atk_JC_JC" },
	{ 1140u, "Atk_B_B_B" },
	{ 1141u, "Atk_C_C_C" },
	{ 1150u, "Atk_AddCommand1" },
	{ 1151u, "Atk_AddCommand2" },
	{ 1152u, "Atk_AddCommand3" },
	{ 1153u, "Atk_AddCommand4" },
	{ 1154u, "Atk_AddCommand5" },
	{ 1155u, "Atk_AddCommand6" },
	{ 1156u, "Atk_AddCommand7" },
	{ 1157u, "Atk_AddCommand8" },
	{ 1158u, "Atk_AddCommand9" },
	{ 1159u, "Atk_AddCommand10" },
	{ 1160u, "Atk_AddCommand11" },
	{ 1306u, "CallSupport4or6" },
	{ 1307u, "CallSupport" },
	{ 1395u, "GCAttackEX_Std" },
	{ 1396u, "GCAttack_Std" },
	{ 1500u, "Basic_AddMove1" },
	{ 1501u, "Basic_AddMove2" },
	{ 1502u, "Basic_AddMove3" },
	{ 1503u, "Basic_AddMove4" },
	{ 1504u, "Basic_AddMove5" },
	{ 1505u, "Basic_AddMove6" },
	{ 1506u, "Basic_AddMove7" },
	{ 1507u, "Basic_AddMove8" },
	{ 1508u, "Basic_AddMove9" },
	{ 1509u, "Basic_AddMove10" },
	{ 1510u, "Basic_AddMove11" },
	{ 1511u, "Basic_AddMove12" },
	{ 1512u, "Basic_AddMove13" },
	{ 1513u, "Basic_AddMove14" },
	{ 1514u, "Basic_AddMove15" },
	{ 1515u, "Basic_AddMove16" },
	{ 1516u, "Basic_AddMove17" },
	{ 1517u, "Basic_AddMove18" },
	{ 1518u, "Basic_AddMove19" },
	{ 1519u, "Basic_AddMove20" },
	{ 1520u, "Basic_AddMove21" },
	{ 1521u, "Basic_AddMove22" },
	{ 1522u, "Basic_AddMove23" },
	{ 1523u, "Basic_AddMove24" },
	{ 1524u, "Basic_AddMove25" },
	{ 1620u, "Crouch" },
	{ 1621u, "Walk_F" },
	{ 1622u, "Walk_B" },
	{ 1908u, "ConvertCharge" },
	{ 1950u, "CallEscapeSupportKirifuda" },
	{ 1951u, "CallEscapeSupport" },
	{ 2000u, "Debug00" },
	{ 2001u, "Debug01" },
	{ 2002u, "Debug02" },
	{ 2003u, "Debug03" },
	{ 2004u, "Debug04" },
	{ 2005u, "Debug05" },
	{ 2006u, "Debug06" },
	{ 2007u, "Debug07" },
	{ 2008u, "Debug08" },
	{ 3199u, "ReversalNeutral" },
};

const Named kPatterns[] = {
	{ 0u, "Neutral" },
	{ 1u, "Atk_StdA" },
	{ 2u, "Atk_StdB" },
	{ 3u, "Atk_StdC" },
	{ 4u, "Atk_CroA" },
	{ 5u, "Atk_CroB" },
	{ 6u, "Atk_CroC" },
	{ 7u, "Atk_AirA" },
	{ 8u, "Atk_AirB" },
	{ 9u, "Atk_AirC" },
	{ 10u, "Walk_F" },
	{ 11u, "Walk_B" },
	{ 12u, "Crouch" },
	{ 13u, "Crouch_Wait" },
	{ 14u, "Crouch_toN" },
	{ 15u, "Furimuki_S" },
	{ 16u, "Furimuki_C" },
	{ 17u, "GuardS" },
	{ 18u, "GuardC" },
	{ 19u, "GuardA" },
	{ 35u, "Jump_F" },
	{ 36u, "Jump_N" },
	{ 37u, "Jump_B" },
	{ 38u, "MultiJump_F" },
	{ 39u, "MultiJump_N" },
	{ 40u, "MultiJump_B" },
	{ 43u, "ForwardShift" },
	{ 45u, "Dash_F" },
	{ 46u, "Dash_B" },
	{ 49u, "StandbyWait" },
	{ 50u, "Standby_1" },
	{ 51u, "Standby_2" },
	{ 52u, "Win" },
	{ 53u, "RoundWin" },
	{ 55u, "Throw_F" },
	{ 56u, "Throw_F_TechWait" },
	{ 57u, "Throw_F_Hit" },
	{ 60u, "GuardCancelAtk" },
	{ 67u, "AirDash_F" },
	{ 68u, "AirDash_B" },
	{ 248u, "TimeupLose" },
	{ 259u, "IWEAtk" },
	{ 260u, "Liberate" },
	{ 261u, "Convert" },
	{ 262u, "ChainShift" },
	{ 401u, "Atk_DashStdA" },
	{ 402u, "Atk_DashStdB" },
	{ 403u, "Atk_DashStdC" },
	{ 404u, "Atk_DashCroA" },
	{ 405u, "Atk_DashCroB" },
	{ 406u, "Atk_DashCroC" },
	{ 407u, "Atk_DashAirA" },
	{ 408u, "Atk_DashAirB" },
	{ 409u, "Atk_DashAirC" },
	{ 997u, "EXCutinGrp" },
	{ 998u, "IWCutinGrp" },
	{ 999u, "IWXCutinGrp" },
};

const Named kMoveCode[] = {
	{ 1u, "Atk" },
	{ 2u, "Skill" },
	{ 4u, "FireBall" },
	{ 8u, "AtkBlade" },
	{ 16u, "Recovery" },
	{ 32u, "Throw" },
	{ 64u, "EXAction" },
	{ 128u, "SPAction" },
	{ 256u, "NoJumpCansel" },
	{ 512u, "BCAction" },
	{ 1024u, "NoBursted" },
	{ 2048u, "NoBurst" },
	{ 4096u, "HitStatus_Damage" },
	{ 8192u, "HitStatus_Guard" },
	{ 16384u, "DoujiCanselNG_NormalAtk" },
	{ 32768u, "CharaFlag1" },
	{ 65536u, "CharaFlag2" },
	{ 131072u, "NoSend_ScriptKnockBackVecor" },
	{ 262144u, "GRDLowBreak" },
	{ 524288u, "GRDBreak_FatalDmgHosei" },
	{ 1048576u, "Sousai" },
	{ 2097152u, "Sousai_NoSubHitCount" },
	{ 4194304u, "Sousai_EnemySubSuccess" },
	{ 8388608u, "FireBallRect" },
	{ 33554432u, "ExDamageHosei" },
	{ 67108864u, "EnableAirAtkStatus" },
	{ 134217728u, "Shielded" },
	{ 268435456u, "EnableCansel_SkilltoSkill" },
	{ 536870912u, "EnableCansel_SkilltoAtk" },
	{ 1073741824u, "EnableCansel_SkilltoJump" },
};

const char* const kPaletteNames[][40] = {
	{ "Black Eclipse", "Twinkle White", "Darkness Tempest", "Light Forest", "Nightmare", "Red Pearl", "Desert Wolf", "Sea Water", "Moonlight", "Justice Rose", "Blau Blitz", "Sunlight Red", "Vortex Galaxy", "Cremisi Grotta", "Holiness Star", "Rosa Descendiente", "Juillet Averse", "Soul Lover", "Caldo Trrente", "Viridis Regulus", "Shinku", "Blanche Diable ", "Ocean Arctique", "Citrus Fresh", "Guilty Thorn", "Schon Gift", "Nutty Pastel", "Clear Gale", "Santana", "Dark Master", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Canary Yellow", "Solitude Spica", "Rhodorite Garnet", "Sylvania Keeper", "Purple Powder", "Pure Black", "Ore Shine", "Blue Ocean", "Autumnal Leaves", "Destruction Red", "Brosche Saphir", "Drought Ground", "Acero Granizo", "Isora Albero", "Wind of Oasis", "Perfume Lemon", "Ciruela", "Pupil Gloomy", "Arche wave", "Ritual Sacrifice", "Spring Breeze", "Lapin de Neige", "Nacht Kirschblute", "Bush Camouflage", "Misty Crystal", "Exotic Coral", "Spunky Mint", "Burial Agency ", "Water Imp", "Nagger Brawny", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Iron Beast", "Crow Ash", "Steel Tiger", "Sapphire Bear", "Magnetite Crystal", "Coal Monster", "Francium Maroon", "Tungsten Yellow", "Poison Bandit", "Hihiirokane", "Fegefeuer", "Arctic Cold", "Dschungel Wind", "Hatred Flame", "Eis mann", "Bestie Erde", "Kirschbaum", "Depression Mind", "Gray Fox", "Apostle of Chaos", "Big Foot", "Crimson Ogre", "Brawny Orc", "Scorched Earth", "Thor's Hammer ", "Red Hot Steel", "Vert Nil", "Ashputtel", "Drema Warden", "Gold Lowe", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Red Heat Blood", "Black Punishment", "Aqua Regia", "Ride on Light", "Dead and Violet", "Bloody Lost", "Wild Fang", "Bad Peace Forest", "Fade Noise", "Purplish Gouache", "Strange Strawberry", "Plena Noche", "Emerald Island", "Ortensia", "Light of Daybreak", "Flash Magic", "Claro de Luna", "Brave Satan", "Peligro Diosa", "Demon Angel", "Crimson Surfer ", "Fake Hero", "Liquid Metal", "Noble Blood", "Vegetarian", "Mr.Monochrome", "Surfusion Eau", "Prunella Honey", "Western Feast", "Dead and Black", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Justice Sprite", "Night Shade", "Tears of Salamander", "Saint's Mother", "Storm Sylphid", "Undine Rain", "Athena Light", "Evil Knight", "Scamper Emerald", "Efreet Flare", "Rizo de Agua", "Fallen Angels", "Dios de la Muerte", "Calm Pink", "Orange Yogurt", "Crimson Rouge", "Mistilteinn", "Green Magnolia", "Lluvia Medium", "Moon Water", "Alice Blue", "Spectrum Rose", "Campanula Purple", "Cavalier Du Lac", "Dry Blood", "Walder Abendrot", "Shade Gardian", "Honorable Scar", "Lumiere Solaire", "Memorial Black", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Robbery Purple", "The Baron of Night", "Poseidon", "Red Azrael", "Thunderbird", "Vampire and Alcohol", "Lancelot du Lac", "Bamboo Scythe", "Season of Harvest", "Legend Vermilion", "Scharlachrot", "Fresco Verde", "Shadow Vice", "Emperor of Walnut", "Mischievous Firefly", "Turquoise Blue", "Atonement Blood", "Golden Summer", "Hard Sleet", "Frost Skeleton", "Gusty Edge", "Noble Impulse", "Amore Formaggio", "Jade Tempest", "Deadvlei", "False Dawn", "Lunar Corona", "Falconry Hawking", "Righteous Daddy", "Imitate Intrigant", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Hell's Viper", "Scallop", "Brown Lizard", "Scream Hades", "Green Iguana", "Bloody Basilisk", "Violet Naja", "Sea Snake", "Dust Sand", "Hephaistos", "Wise Marlin", "Noble Turtle", "Ladybug", "Sauterelle Prince", "Rose Crane", "Lark Dancer", "Cruel Penguin", "Killer Bee", "Sombre Corbeau", "Humble Falcon", "Lila Giftschlange", "Flamme Haare", "Blume Strum", "Abitante de Vulcano", "Gloomy Violet", "Orange A La Mode", "Gewitterwolke", "Forest Gorilla", "Motor Schlange ", "Marchen Merkava", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Mars Black", "lion Falls", "Murder Dolls", "Aurora Blue", "Aureolin", "Classic White", "Luminous Pink", "Fallen Leaves", "Chromium Green", "Crimson Lake", "Lila Colina", "Azul Agua", "Regalo Tierra", "Freddo Aria", "Grass Fairy", "Donner Geist", "Black Magic", "Knospe Gardenie", "Rain Stream", "Flor Ciruela", "Cassata Al Forno", "Moonshine Blue", "Vento Aureo", "Angelic Gospel", "Cyber Fairy", "Blitzschlag", "Mystic Doll", "Antique Luxury", "Modern Golem", "Fairy Tale", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Shadow Approaches", "Light is Refuse", "Rain Murder", "Coin and Balance", "The Edge of Poison", "Light in Darkness", "Ashes Incinerator", "Clothed in Fire", "Natural Tree", "Nightcap Wine", "Coral Comet", "Glorious Brown", "Cosmos Black", "Pulito Foschia", "Cerisier", "Ombra Abisso", "Luna Mezzanotte", "Mountain July", "Sunrise Yellow", "Hawk Sign", "Slight Haze", "Desert Rose", "Lunatic Clown", "Crimson Meteor", "Migratory Locust", "Monochrome Mirage", "Spring Blizzard", "Ruby Ball", "Deep Forest Venerer", "Banded Krait", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Chaenomeles Sinensis", "Siberian Iris", "Betula Grossa", "Water Drips", "Successful Black", "Globe Amaranth", "Snow Drop", "Autumn Flower", "Gold Rush", "Cluster Amaryllis", "Cherry blossom", "Dandelion", "Underwater Sun", "Shrine Maiden", "Four Leaves", "Dies Irae", "Golden Done", "Twig Palm", "Ghiaccio Luce", "Heliconiaceae", "The New Squad", "Short Circuit", "Muddied Lady", "Sea Soldier", "Morning Glory", "Vermilion Eye", "Summer Heat Haze", "Freesia Refracta", "Black Rabbit", "Primrose Yellow", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Morion Black", "Brightness Amethyst", "Beauty of Elysion", "Half of Indigolite", "Fire Ruby", "Sapphire", "Eroded Peridot", "Golden Beryl", "Calm in Passion", "Blood Andesine", "Ice Age", "Laurel Tiara", "Black Crimson", "Aquamarine", "Forest of Witch", "Zinnoberrot Gelb", "Cor de Rosa", "Cool Purple", "Illuminate White", "Mal Despiadado", "Gold and Silver", "Lava Flow", "Astuto Signora", "Schneefee", "End of Fall", "Elegant Dunkelgrun", "Juvenile Colors", "Spring Phantasma", "Sapphire Splash", "Rose Garden", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Alchemist", "Black Barrel", "Fleeting Lover", "Great Sphynx", "Fang and Nail", "Transylvania's Ghost", "Wing of Horus", "Aswan Falucca", "Psycho Garden", "Living Dead", "Dunkelheit", "Burn Gem", "Nostalgia", "Silence Iceberg", "Neo Venus", "Bello Girasole", "Summer Vacation", "Amore Pesco", "Jet Black", "Snow Fairy", "Celadon Narcissus", "Nile Over Knee", "Girl Scout", "Somei Yoshino", "Desert Platoon", "Blanc Neige", "Gloom Neon", "Peacock Leaf", "Vivid Navy Blue ", "Phantasmal Candle", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Moulin a Vent", "Altar of Iris", "Blitz Flugel", "Averse Ciel", "Katze Madchen", "Nature Gale", "Deesse Luna", "Sol Envidia", "Glicina Boton", "Mars Soir", "Freeze Night", "Thin Vermilion", "Vert Clair de Lune", "Glamorous Aura", "Notre Dame", "Apricot Tea", "Stille Vulkan", "Briny Air", "Winter Nacht", "Otaria Bianco", "Juillet Peche", "Le Lac Des Fees", "Insulator Girl", "Grizzled Doe", "Stratosphere", "Ginkgo biloba", "Chitose Green", "Luft Minze", "Depletion Garden", "Mystique Senior   ", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Midnight Spider", "Hell Smoke", "Ende Regen", "Drought Earth", "Rotten Pomegranate", "Falsehood Night", "Maple October", "Dirty Wisteria", "Bamboo Spear", "Withered Lilac", "Blue Ripple", "Another Galaxy", "Knight of Mercury", "Mud Crater", "Bottom to Abyss", "Desert Sun", "Flash White", "Fullmoon Light", "Cunning Tiger", "Valley Magnolia", "Spurt of Blood", "Deep Azalea", "Madness Glow", "Attack of the Orange", "Gletscher Stachel", "Plage Soleil", "Creeping Villain", "Tricolor trooper", "Rose Thorn", "Norland Sibling", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Blanc Rouge", "Strong Red", "Freeze Crest", "Vestige Garrigue", "Idesl Empire", "Snow Harbor", "Neve Tempo", "June Sprout", "Viola Notte", "Puro Vizio", "Pond Mars", "Neve Granulosa", "Smaragd Fluss", "Cloudy Weather", "Primerose Flavor", "Wildness Parakeet", "Landa Sereno", "Glanz Eis", "Crepuscolo Lampo", "Diablo Noche", "Marine Striker", "Living God", "Pixy Pink", "Western Traveler ", "Noix Rouge", "Fighting Blaster", "March Into Snow", "Oceanic Depths", "Aufblitzen Motor", "Dunkel Motor", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Prateria Lupo", "Iceberg Lince", "Vulcano Squalo", "Mare Leone", "Landa Vipera", "Altopiano Serpente", "Giallo Gatto", "Verde Bestia", "Aldebaran", "Grazia Fuoco", "Jellyfish", "Cremation Heretic", "Moos Licht", "Eclipse Day", "Lapis Lazuli", "Orquidea Submundo", "Heat Haza", "Nuit Tonnerre", "Ground Horizon", "Uninhabited Island", "Regal Crest", "Urban Camouflage", "Planet Snatcher", "Daphne Gray", "Squash Yellow", "Grapy Amethyst", "Unter Vulkan", "R.Fox & G.Raccoon", "Ceresso Bestia", "A Mere Buddy", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Judgement Blazer", "White Lily", "Viking Blue", "Dark Nebula", "Sharply Uvarovite", "Abyss Walker", "Eschscholtzia", "Shadowy Iris", "Beauty Gladiator", "Vermillion Edge", "Eis Herrscher", "Bloodlust", "Rapturous Green", "Hazy Moon Night", "Tiefsee Botschafter", "Noble Fencer", "Vivid Scarlet", "Amethyst Sowrd", "Sand Rose", "Rage of Nature", "Schelt Frau", "Nacht Garten", "Sakura Blade", "Sacred Saber", "Autumn Abundance", "Maidenly Rose", "Dripping Blood", "Icicle Pink", "Vidofnir Feather", "Longevity Witch", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Saika Kissui", "Sekishu Kuuken", "Ryokurin hakuha", "Uguisu", "Shiden Seisou", "Kaikatsu Tenkuu", "Jinrai Furetsu", "Meimei Hakuhaku", "Kakou Ryuryoku", "Netsugan Reitei", "Suo", "Masuhana", "Hakusha Seisyo", "Akesumire", "Nobori Arashi", "Hanada Kohaku", "Sakura Mochi", "Koujin Banjo", "Awa Chidori", "Tanpopo", "Ume Murasaki", "Seiten Hekireki", "Raito Unpon", "Yama Budo", "Hanarokusyo", "Akane Aokachi", "Kaisei Sanmei", "Tsuki Some", "Aoni Fukahi", "Tansyo Noumatsu", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Frosty Knight", "Moon Shade", "Imperial Jade", "Bernstein", "Tranquille Mauve", "Prototype Executor", "Blood Oath", "Glacier Light", "Assassins Edge", "Glimpse of Devil", "Antarctic Emperor", "Cyanotype", "Vampire Lord", "Sherwood Shooter", "Dokkalfar", "Visonary Myst", "Rosa Moyesii", "Zeit ist Geld", "Styx Driftice", "Celestial Nation", "Jung Monarch", "Morning Dew", "Fruhling Nacht", "Flugel Ritter", "Eschatos Daylight", "Military Officer", "Ice Magician", "Heartless Fellow", "End of October", "Grape Sherbert", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Bright Cliff", "Sapphire Knight", "Ancient Green", "Calm Light", "Crepuscular Sea", "Flame in the Dark", "Flax Gray", "Deep Shark", "Volcanic Rumbling", "Confederate Blood", "Beyond the Horizon", "Late Night Ocean", "Arctic Haze", "Forest Guard", "Aggressive Plum", "Desert Candle", "Mint Distillation", "Hestina Japonica", "Black Mustard", "Capsicum Annuum", "Cave Explorer", "Purple Electric", "Abyss Green", "Microwave Oven", "Twilight Zone", "Earth Intensity", "Eternal Time", "Pastel Vision", "Scabiosa Violet", "Dim Red", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Black Monger", "Death Sickle", "Nameless Weed", "Ahead of Season", "Midnight Sea", "Ominous Flower", "Doubtful Apothecary", "Posthumous Glory", "Yay Portrait", "Death Dealer", "Falsify Innocense", "Meaning of Love", "Pumpkin Magic", "Aquatic Astrology", "Desert Cactus", "Bloodstained Hand", "Evil Druid", "Overgrow Herb", "Crimson Raider", "Desert Paradise", "Queen of Wonderland", "Antique Doll", "Amo il Formaggio", "Halloween Devil", "Aquatic Witch", "Ignis Fatuus", "Last Leaf", "Ms. Aquarium", "Miserable Clover", "Saucy Little Devil", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Firmament Bullet", "Rose Jasper", "Frisches Grun", "Lowenzahn", "Impish Lightning", "Swimmy Azure", "Black Diamond", "Energy Sign", "Petty Rose", "Vinous Arm", "Sunny Promenade", "Queen Valet", "Fragrant Green", "Meteor Impact", "Sunglow Cloud", "Petit Tigre", "Sea of Tranquility", "Puppyish Girl", "Spicy Crab", "Glacial Blow", "Immeasurable Comet", "Secret Garden", "Sorrent Gold", "Plic Ploc", "Dragon Bless", "Tiny Dwarf ", "Midnight Sun", "Radiant Gauntlet", "Electroactuation", "Lucky Clover", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Urbane Banisher", "Blood Countess", "Bouncing Yellow", "Calm Atmosphere", "Almost Night", "Shady Chaser", "Autumn Stroll", "Special Gospel", "Ice Dance", "Witch of the Gun", "Shrine Maiden", "Striking Vermillion", "Sour-Sweet Fruit", "Light And Shadow", "Sand Storm", "Green Tea", "Vampire Affectation", "Tropical Lady", "Call From Deep Sea", "Miss Valentine", "Dancing Dragon", "Neighborhood Lady", "Beat Angel", "Berserk Gunner", "Matcha to Anko", "Deep Red Dress", "Acquired Taste", "Secret Business", "Radiant Firearm", "Spiral Pierce", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Total Eclipse", "Fallen Sunlight", "Green Flash", "Deep Light", "Twilight Fire", "Redshift", "Dark Matter", "Bright Nebula", "Cosmic Microwave", "Red Dwarf", "Forest Kingdom", "Bright Giant", "Brine Pool", "Sunset Glow", "Flaming Illusion", "Endless Guilty", "Chaos Chronicle", "Disaster Genesis", "Mirage Emblem", "Grudge Stigma", "Sacred Dogma", "Ruin Fragment", "Inferno Vortex", "Dystopia Matrix", "Strange Eclipse", "Arcadia Demise", "Calamity Sinner", "Moonlight Canon", "Crisis Nexus", "Criminal Legion", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Snake Keeper", "Purple Pain", "Emerald Seaserpent", "Sugaar Lightning", "Rosaceous Naga", "Green Thorn", "Navy Lindworm", "Aiatar's Forest", "Fafnir Rouge", "Goddess Underworld", "Twilight Nidhoggur", "Cutie Quetzalcoatl", "Lahamu Cherry", "Lamia Amethyst", "Ladon Brown", "Wish of Melusine", "Brilliant Leviathan", "Egger Aitvaras", "Kukulkan Green", "Sunburned Itzamna", "Tiny Midgard", "Hydra Swamp", "Punane Pisuhand", "Blame Vouivre", "Azzurro Amphisbaena", "Blessed Itzamna", "Ouroboros Hue", "Red Castle", "Coatlicue Harvest", "Hoydenish Breeze", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Abyss Returner", "From the Ash", "Epilithic Moss", "Marine Style", "Old Gentleman", "Lady Killer", "Blood Starved Beast", "Newbie Agent", "Dweller Back Alley", "Blood Nocturne", "Rock Star", "Jade Harvester", "Shiden Strike", "Stony Contract", "Gold Surfer", "Winter Land", "Hero Appearance", "Majestic Clan", "Meadow Wind", "White Smoke", "Madam's Guardians", "Blue Curacao", "Jolly Brother", "Loxley Impact", "Birth In-Peach", "Sea Breeze", "Treasure Map", "Spilled Red", "Desert River", "Shadow Chaser", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
	{ "Night Mermaid", "Call of Abyss", "Lemon Tea", "Verdure Wind", "Pink Bomb", "Swimming Club", "Wasserpflanzen", "Chairwoman", "Dune Wave", "Chrysaora pacifica", "Coral Palace", "Goldfish Bowl", "Moonlit Bathe", "Sanatorium", "Metalworking", "Mimosa Garden", "Low Pressure Girl", "Many Spices", "Pink Neon", "Allium Fistulosum", "Concealed Clan", "Rushing Heat", "Genoa Fortuneteller", "Sickly Sister", "Flaming Mountain", "Spring Poems", "Incongruous Purple", "Electric Leakage", "Futuristic Plant", "Unbeatable Heroine", "Equatorial Wave", "Inferno Blaze", "Annular Eclipse", "Seeds of Heaven", "Clamorous Colors", "Royal Calibur", "Stella Nest", "Little Briar Rose", "Betrayal of Savior", "Switching Contrast" },
};

constexpr int kPaletteCharaCount = 27;
constexpr int kPaletteNameCount = 40;

const unsigned char kPart00_0[] = { 16, 17, 18, 19, 20, 22, 23, 29 };
const unsigned char kPart00_1[] = { 112, 113, 114, 115 };
const unsigned char kPart00_2[] = { 70, 71, 72, 73, 75, 76, 77, 78, 79, 80, 81, 82, 83 };
const unsigned char kPart00_3[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 15, 38, 39, 40, 41, 42, 43 };
const unsigned char kPart00_4[] = { 96, 97, 98, 99, 101, 102, 104, 105, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169 };
const unsigned char kPart01_0[] = { 8, 9, 10, 11, 12, 14 };
const unsigned char kPart01_1[] = { 81, 82, 83, 84, 85 };
const unsigned char kPart01_2[] = { 88, 89, 90, 91, 92, 96, 97, 98, 99, 100, 101, 103, 104, 105, 106, 123, 124, 125, 126, 127 };
const unsigned char kPart01_3[] = { 1, 2, 3, 4, 5, 16, 17, 18, 19, 20, 21, 22, 23, 192, 193, 194, 195, 196, 197, 198, 199, 201, 202, 203, 254, 255 };
const unsigned char kPart01_4[] = { 128, 129, 130, 131, 133, 134, 135, 136, 144, 145, 146, 147, 148, 149, 150, 151, 160, 161, 162, 163, 164, 165, 166, 167, 205, 206, 207, 208, 210, 211, 212, 213, 215, 216, 217 };
const unsigned char kPart02_0[] = { 32, 33, 34, 35, 36 };
const unsigned char kPart02_1[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10 };
const unsigned char kPart02_2[] = { 121, 122, 123, 124 };
const unsigned char kPart02_3[] = { 112, 113, 114, 115 };
const unsigned char kPart02_4[] = { 48, 49, 50, 51, 52, 54, 55, 56, 57, 58 };
const unsigned char kPart02_5[] = { 74, 75, 76, 77, 78, 79, 183, 184, 185, 186, 187, 188, 189, 190, 191 };
const unsigned char kPart03_0[] = { 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 75, 76, 77, 78 };
const unsigned char kPart03_1[] = { 43, 44, 45, 46 };
const unsigned char kPart03_2[] = { 24, 25, 26, 27, 64, 65, 66, 67, 68, 69, 71, 72, 82, 83, 84, 85 };
const unsigned char kPart03_3[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 };
const unsigned char kPart03_4[] = { 113, 114, 115, 116, 117, 118, 119, 120 };
const unsigned char kPart04_0[] = { 16, 17, 18, 19, 20, 22, 23, 32, 236, 237, 238 };
const unsigned char kPart04_1[] = { 54, 55, 56, 57, 58, 252, 253, 254, 255 };
const unsigned char kPart04_2[] = { 70, 71, 72, 73, 74, 80, 81, 82, 83, 84, 224, 225, 226, 227 };
const unsigned char kPart04_3[] = { 96, 97, 98, 99, 100, 102, 103, 104, 105, 106, 112, 128, 129, 130, 132, 133, 134, 135, 136, 160, 161, 162, 163, 164, 166, 167, 168, 169, 170, 172, 173, 174, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 220, 221, 222, 223 };
const unsigned char kPart04_4[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 15, 24, 25, 26, 27, 28, 64, 65, 66, 67, 68, 138, 139, 140, 141, 142, 192, 193, 194, 195, 196, 197, 231, 232, 233, 234 };
const unsigned char kPart05_0[] = { 20, 21, 22, 23, 25, 27 };
const unsigned char kPart05_1[] = { 96, 97, 98, 99 };
const unsigned char kPart05_2[] = { 71, 72, 73, 74, 75, 87, 88, 89, 90, 91 };
const unsigned char kPart05_3[] = { 128, 129, 130, 131, 160, 161, 162, 163, 164, 165, 166, 168, 169, 170, 171, 224, 225, 226, 227, 228, 229, 230, 231, 232, 235, 236, 237 };
const unsigned char kPart05_4[] = { 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 14, 15 };
const unsigned char kPart06_0[] = { 16, 17, 18, 19, 20, 21 };
const unsigned char kPart06_1[] = { 27, 28, 29, 30, 31 };
const unsigned char kPart06_2[] = { 11, 12, 13, 14, 15, 36, 37, 39, 40, 41, 43, 44 };
const unsigned char kPart06_3[] = { 0, 7, 8, 9 };
const unsigned char kPart06_4[] = { 0, 254, 255 };
const unsigned char kPart07_0[] = { 16, 17, 18, 19, 20, 21, 22, 24, 25 };
const unsigned char kPart07_1[] = { 27, 28, 29, 30, 31, 64, 65, 66, 67, 68 };
const unsigned char kPart07_2[] = { 54, 55, 56, 57, 58, 70, 71, 72, 73, 74, 76, 77, 144, 145, 146, 147, 148, 150, 151, 152, 153, 154 };
const unsigned char kPart07_3[] = { 88, 89, 90, 92, 93, 94, 118, 119, 120, 122, 123, 124, 125, 126, 138, 139, 140, 142, 143 };
const unsigned char kPart07_4[] = { 1, 2, 3, 4, 5, 7, 8, 9, 11, 12, 13, 15, 80, 81, 82, 83, 84, 112, 113, 114, 115, 116, 254, 255 };
const unsigned char kPart08_0[] = { 16, 17, 18, 19, 20 };
const unsigned char kPart08_1[] = { 15, 21, 22, 23, 24, 25 };
const unsigned char kPart08_2[] = { 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68 };
const unsigned char kPart08_3[] = { 96, 97, 98, 99, 100, 112, 113, 114, 115 };
const unsigned char kPart08_4[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 27, 28, 29, 31, 102, 103, 104, 105, 106, 107, 108, 118, 119, 120, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 171, 172, 173, 174 };
const unsigned char kPart09_0[] = { 16, 17, 18, 19, 20, 32 };
const unsigned char kPart09_1[] = { 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 128, 129, 130, 131, 132, 133, 135, 136 };
const unsigned char kPart09_2[] = { 80, 81, 82, 83, 84, 92, 93, 94, 95, 96, 97, 98, 99, 100 };
const unsigned char kPart09_3[] = { 86, 87, 88, 89, 90, 103, 104, 105, 106, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 224, 225, 226, 228, 229, 230, 232, 233, 234, 236, 237, 238, 239, 240, 241, 243, 244, 245, 246, 248, 249, 250 };
const unsigned char kPart09_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 22, 23, 24, 31 };
const unsigned char kPart10_0[] = { 16, 17, 18, 19, 20, 21, 23, 24 };
const unsigned char kPart10_1[] = { 32, 33, 34, 80, 81, 82, 83, 85, 86, 87, 88, 90, 91, 92, 93, 94, 95 };
const unsigned char kPart10_2[] = { 96, 97, 98, 99, 100 };
const unsigned char kPart10_3[] = { 128, 129, 130, 131, 132 };
const unsigned char kPart10_4[] = { 1, 2, 3, 4, 5, 6, 26, 27, 28, 29, 30, 31, 144, 145, 146, 147, 148, 150, 151, 152, 153, 154 };
const unsigned char kPart11_0[] = { 16, 17, 18, 19, 20, 31, 32 };
const unsigned char kPart11_1[] = { 176, 177, 178, 179, 180, 240, 241, 242, 243, 244, 245, 247, 248, 249, 251, 252 };
const unsigned char kPart11_2[] = { 144, 145, 146, 147, 148 };
const unsigned char kPart11_3[] = { 54, 55, 56, 57, 80, 81, 82, 83, 84, 112, 113, 114, 115, 116 };
const unsigned char kPart11_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 22, 23, 24, 25, 27, 28, 29, 192, 193, 194, 195, 196, 197, 208, 209, 210, 211, 212, 213, 224, 225, 226, 227, 228, 229 };
const unsigned char kPart12_0[] = { 15, 16, 17, 18, 19, 20, 26 };
const unsigned char kPart12_1[] = { 54, 55, 56, 57, 58, 64, 65, 66, 67, 68, 80, 81, 82, 83, 84 };
const unsigned char kPart12_2[] = { 128, 129, 130, 131, 132, 144, 145, 146, 147, 148, 160, 161, 162, 163, 164 };
const unsigned char kPart12_3[] = { 192, 193, 194, 195, 196, 198, 199, 200, 201, 202, 203, 208, 209, 210, 211, 212, 215, 216, 217, 218, 219, 224, 225, 226, 227, 228, 229, 230, 232, 233, 234 };
const unsigned char kPart12_4[] = { 1, 2, 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 22, 23, 24, 31, 32, 33, 34, 35, 36, 44, 150, 151, 152, 153, 154, 155, 157, 167, 168, 169, 171, 172, 173 };
const unsigned char kPart13_0[] = { 15, 16, 17, 18, 19, 20, 32, 208, 209, 210, 211, 212 };
const unsigned char kPart13_1[] = { 112, 113, 114, 115, 116, 118, 119, 120, 121, 123, 124, 125, 126, 127, 240, 241, 242, 243 };
const unsigned char kPart13_2[] = { 64, 65, 66, 67, 68, 70, 71, 80, 81, 82, 83, 84, 230, 231, 232 };
const unsigned char kPart13_3[] = { 172, 173, 174, 175, 220, 221, 222, 223, 251, 252 };
const unsigned char kPart13_4[] = { 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 13, 144, 145, 146, 147, 148, 150, 151, 152, 160, 161, 162, 163, 164, 166, 167, 168, 169, 170, 193, 194, 195, 196, 197, 198, 199, 201, 202, 203, 205, 246, 247, 248, 249, 250 };
const unsigned char kPart14_0[] = { 15, 16, 17, 18, 19, 20, 21 };
const unsigned char kPart14_1[] = { 128, 129, 130, 131, 132, 134, 135, 136, 137, 138, 144, 145, 146, 147, 148 };
const unsigned char kPart14_2[] = { 48, 49, 50, 51, 52, 53, 54, 55, 56, 61, 62, 63, 208, 209, 210, 211, 212 };
const unsigned char kPart14_3[] = { 160, 161, 162, 163, 164, 166, 167, 168, 169, 170, 172, 173, 174, 175, 176 };
const unsigned char kPart14_4[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 85, 86, 87, 88, 89, 91, 92, 93, 94, 95 };
const unsigned char kPart15_0[] = { 16, 17, 18, 19, 20, 22, 33, 230, 231, 232, 233 };
const unsigned char kPart15_1[] = { 128, 129, 130, 131, 132, 144, 145, 146, 147, 148, 160, 161, 162, 163, 164, 224, 225, 226, 227 };
const unsigned char kPart15_2[] = { 27, 28, 29, 30, 31, 43, 44, 45, 46, 47, 176, 177, 178, 179, 181, 182, 183, 184, 186, 187, 188, 189, 190, 240, 241, 242, 243 };
const unsigned char kPart15_3[] = { 135, 136, 137, 138, 140, 141, 151, 152, 153, 154, 156, 157, 158, 245, 246, 247 };
const unsigned char kPart15_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 13, 15, 24, 25, 26, 106, 107, 108, 109, 110, 111, 214, 215 };
const unsigned char kPart16_0[] = { 16, 17, 18, 19, 20, 22 };
const unsigned char kPart16_1[] = { 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 60, 61, 62, 63, 86, 87, 88, 89, 90, 96, 97, 98, 99, 100 };
const unsigned char kPart16_2[] = { 112, 113, 114, 115, 116, 117, 128, 129, 130, 131, 132, 133, 203, 204, 205, 206, 207, 213, 214, 215, 216, 218, 219, 220, 221, 222, 223, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239 };
const unsigned char kPart16_3[] = { 119, 120, 121, 122, 123, 135, 136, 137, 138, 139, 144, 145, 146, 147, 148, 149, 151, 152, 153, 154, 155, 167, 168, 169, 170, 171 };
const unsigned char kPart16_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 13, 15, 160, 161, 162, 163, 164, 165, 192, 193, 194, 195, 196, 208, 209, 210, 211, 212, 224, 225 };
const unsigned char kPart17_0[] = { 32, 33, 34, 35, 36, 38 };
const unsigned char kPart17_1[] = { 1, 2, 3, 4, 5, 7, 8, 9, 11, 12, 13, 15 };
const unsigned char kPart17_2[] = { 17, 18, 19, 20, 21 };
const unsigned char kPart17_3[] = { 96, 97, 98, 99, 100 };
const unsigned char kPart17_4[] = { 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 136, 137, 138, 139, 140, 160, 161, 163, 164, 165, 166, 167, 169, 170, 171, 179, 180, 181, 182, 183 };
const unsigned char kPart18_0[] = { 32, 35, 36, 37, 38, 39, 41, 76, 77 };
const unsigned char kPart18_1[] = { 70, 71, 72, 73, 74, 86, 87, 88, 89, 90, 224, 225, 226, 227, 233, 234, 235, 236, 237, 238, 254, 255 };
const unsigned char kPart18_2[] = { 123, 124, 125, 126, 127, 182, 183, 184, 185, 186 };
const unsigned char kPart18_3[] = { 128, 129, 130, 131, 132, 144, 145, 146, 147, 148 };
const unsigned char kPart18_4[] = { 1, 2, 3, 4, 5, 7, 8, 9, 11, 12, 13, 176, 177, 178, 179, 180, 192, 193, 194, 195, 196, 208, 209, 210, 211, 212 };
const unsigned char kPart19_0[] = { 16, 17, 18, 19, 20, 22 };
const unsigned char kPart19_1[] = { 208, 209, 210, 211, 212, 214, 215, 216, 217, 218, 219, 230, 231, 232, 233, 234, 235 };
const unsigned char kPart19_2[] = { 112, 113, 114, 115, 116 };
const unsigned char kPart19_3[] = { 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 205, 206, 207 };
const unsigned char kPart19_4[] = { 1, 2, 3, 4, 5, 8, 9, 10, 11, 12, 13, 15, 64, 65, 66, 67, 68, 70, 71, 72, 74, 75, 76, 77, 144, 145, 146, 147, 148, 150, 151, 152, 153, 154, 156, 157, 158, 159, 160, 161, 162, 163, 164, 166, 168, 169 };
const unsigned char kPart20_0[] = { 11, 15, 24, 25, 26, 27, 28 };
const unsigned char kPart20_1[] = { 91, 92, 93, 94, 95, 107, 108, 109, 110, 111, 169, 170, 171, 172, 173, 174, 175, 187, 188, 189, 190, 191 };
const unsigned char kPart20_2[] = { 118, 119, 120, 121, 122, 134, 135, 136, 137, 138, 150, 151, 152, 153, 154 };
const unsigned char kPart20_3[] = { 61, 62, 63, 112, 113, 114, 115, 116, 128, 129, 130, 131, 132, 192, 193, 194, 195, 196, 198, 199, 200, 201, 202, 208, 209, 210, 211, 212, 214, 215, 216, 217, 218, 220, 221, 222, 223, 224, 225, 227, 228, 229, 230 };
const unsigned char kPart20_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 13, 17, 18, 19, 20, 21, 22, 160, 161, 162, 163, 164 };
const unsigned char kPart21_0[] = { 15, 64, 65, 66, 67, 68, 69 };
const unsigned char kPart21_1[] = { 128, 129, 130, 131, 133, 134, 135, 136, 192, 193, 194, 195, 196, 198, 200, 201, 202, 203, 204, 208, 209, 210, 211, 213, 214, 215, 217, 218, 219 };
const unsigned char kPart21_2[] = { 112, 113, 114, 115, 116, 118, 119, 120, 121 };
const unsigned char kPart21_3[] = { 17, 18, 19, 20, 21, 22, 23, 28, 29, 30, 33, 34, 35, 36, 37, 38, 39 };
const unsigned char kPart21_4[] = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15, 31, 160, 161, 162, 163, 164, 166, 167, 169, 170, 171, 172, 173 };
const unsigned char kPart22_0[] = { 16, 17, 18, 19, 20, 22 };
const unsigned char kPart22_1[] = { 26, 27, 28, 29, 30, 31, 42, 43, 44, 45, 46, 47, 112, 113, 114, 115, 116, 118, 119, 120, 121, 122, 136, 137, 138, 139, 140 };
const unsigned char kPart22_2[] = { 128, 129, 130, 131, 132, 134, 176, 178, 179, 180, 181, 182, 184, 185, 186 };
const unsigned char kPart22_3[] = { 70, 71, 72, 73, 74, 102, 103, 104, 105, 106, 208, 209, 210, 211, 212, 224, 225, 226, 227, 228 };
const unsigned char kPart22_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 160, 161, 162, 163, 164, 166, 167, 168, 169, 170 };
const unsigned char kPart23_0[] = { 15, 65, 66, 68, 69, 70, 71, 72, 73, 74, 86 };
const unsigned char kPart23_1[] = { 48, 49, 50, 51, 52 };
const unsigned char kPart23_2[] = { 96, 97, 98, 99, 100 };
const unsigned char kPart23_3[] = { 102, 103, 104, 105, 106, 108, 109, 110, 252 };
const unsigned char kPart23_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15 };
const unsigned char kPart24_0[] = { 16, 17, 18, 19, 20, 22 };
const unsigned char kPart24_1[] = { 80, 81, 82, 83, 84, 86, 87, 88, 89, 90 };
const unsigned char kPart24_2[] = { 224, 225, 226, 227, 228 };
const unsigned char kPart24_3[] = { 144, 145, 146, 147, 148, 149, 160, 161, 162, 163, 164, 165, 176, 177, 178, 179, 180, 181, 192, 193, 194, 195, 196, 208, 209, 210, 211, 212 };
const unsigned char kPart24_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 48, 49, 50, 51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 151, 152, 153, 154, 155, 156, 157, 158, 172, 173, 174, 183, 184, 185, 186, 187, 199, 200, 201, 203, 204, 205 };
const unsigned char kPart25_0[] = { 16, 17, 18, 19, 20, 22 };
const unsigned char kPart25_1[] = { 80, 81, 82, 83, 84, 91, 92, 93, 94, 95 };
const unsigned char kPart25_2[] = { 144, 145, 146, 147, 148 };
const unsigned char kPart25_3[] = { 96, 97, 98, 99, 100 };
const unsigned char kPart25_4[] = { 1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 15, 32, 33, 35, 155, 156, 157, 158, 159, 192, 193, 195, 196, 197, 198, 199, 201, 211, 212, 213, 214, 215 };
const unsigned char kPart26_0[] = { 16, 17, 18, 19, 20 };
const unsigned char kPart26_1[] = { 80, 81, 82, 83, 84, 87, 88, 89, 90, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 204, 205, 206, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 220 };
const unsigned char kPart26_2[] = { 112, 113, 114, 115, 116, 118, 119, 120, 121, 122 };
const unsigned char kPart26_3[] = { 22, 23, 24, 25, 38, 39, 40, 41 };
const unsigned char kPart26_4[] = { 1, 2, 3, 4, 5, 6, 7, 8, 11, 12, 13, 14, 15, 27, 28, 29, 30, 31, 144, 145, 146, 147, 148, 150, 151, 152, 154, 155 };

struct Part { const char* name; const unsigned char* entries; int count; };
struct CharaParts { int chara; const Part* parts; int count; };

const Part kParts00[] = {
	{ "Part 1", kPart00_0, 8 },
	{ "Part 2", kPart00_1, 4 },
	{ "Part 3", kPart00_2, 13 },
	{ "Part 4", kPart00_3, 19 },
	{ "Part 5", kPart00_4, 18 },
};
const Part kParts01[] = {
	{ "Part 1", kPart01_0, 6 },
	{ "Part 2", kPart01_1, 5 },
	{ "Part 3", kPart01_2, 20 },
	{ "Part 4", kPart01_3, 26 },
	{ "Part 5", kPart01_4, 35 },
};
const Part kParts02[] = {
	{ "Part 1", kPart02_0, 5 },
	{ "Eyes", kPart02_1, 9 },
	{ "Part 3", kPart02_2, 4 },
	{ "Part 4", kPart02_3, 4 },
	{ "Part 5", kPart02_4, 10 },
	{ "Part 6", kPart02_5, 15 },
};
const Part kParts03[] = {
	{ "Part 1", kPart03_0, 14 },
	{ "Part 2", kPart03_1, 4 },
	{ "Part 3", kPart03_2, 16 },
	{ "Part 4", kPart03_3, 15 },
	{ "Part 5", kPart03_4, 8 },
};
const Part kParts04[] = {
	{ "Hair", kPart04_0, 11 },
	{ "Collar", kPart04_1, 9 },
	{ "Part 3", kPart04_2, 14 },
	{ "Trim", kPart04_3, 47 },
	{ "Skin", kPart04_4, 38 },
};
const Part kParts05[] = {
	{ "Hair", kPart05_0, 6 },
	{ "Trousers", kPart05_1, 4 },
	{ "Part 3", kPart05_2, 10 },
	{ "Belt", kPart05_3, 27 },
	{ "Skin", kPart05_4, 13 },
};
const Part kParts06[] = {
	{ "Hair", kPart06_0, 6 },
	{ "Skin", kPart06_1, 5 },
	{ "Wings", kPart06_2, 12 },
	{ "Eyes", kPart06_3, 4 },
	{ "Part 5", kPart06_4, 3 },
};
const Part kParts07[] = {
	{ "Hair", kPart07_0, 9 },
	{ "Hairpin", kPart07_1, 10 },
	{ "Frill skirt", kPart07_2, 22 },
	{ "Ears", kPart07_3, 19 },
	{ "Skin", kPart07_4, 24 },
};
const Part kParts08[] = {
	{ "Part 1", kPart08_0, 5 },
	{ "Part 2", kPart08_1, 6 },
	{ "Belt", kPart08_2, 13 },
	{ "Trousers", kPart08_3, 9 },
	{ "Skin", kPart08_4, 57 },
};
const Part kParts09[] = {
	{ "Hair", kPart09_0, 6 },
	{ "Sandals", kPart09_1, 18 },
	{ "Leggings", kPart09_2, 14 },
	{ "Blade", kPart09_3, 42 },
	{ "Skin", kPart09_4, 17 },
};
const Part kParts10[] = {
	{ "Hair", kPart10_0, 8 },
	{ "Hairpin", kPart10_1, 17 },
	{ "Part 3", kPart10_2, 5 },
	{ "Part 4", kPart10_3, 5 },
	{ "Skin", kPart10_4, 22 },
};
const Part kParts11[] = {
	{ "Hair", kPart11_0, 7 },
	{ "Shoes", kPart11_1, 16 },
	{ "Skirt", kPart11_2, 5 },
	{ "Metal", kPart11_3, 14 },
	{ "Skin", kPart11_4, 38 },
};
const Part kParts12[] = {
	{ "Hair", kPart12_0, 7 },
	{ "Shirt", kPart12_1, 15 },
	{ "Legs", kPart12_2, 15 },
	{ "Blade", kPart12_3, 31 },
	{ "Skin", kPart12_4, 35 },
};
const Part kParts13[] = {
	{ "Hair", kPart13_0, 12 },
	{ "Slacks", kPart13_1, 18 },
	{ "Shirt", kPart13_2, 15 },
	{ "Part 4", kPart13_3, 10 },
	{ "Skin", kPart13_4, 45 },
};
const Part kParts14[] = {
	{ "Hair", kPart14_0, 7 },
	{ "Part 2", kPart14_1, 15 },
	{ "Collar", kPart14_2, 17 },
	{ "Shoes", kPart14_3, 15 },
	{ "Skin", kPart14_4, 22 },
};
const Part kParts15[] = {
	{ "Hair", kPart15_0, 11 },
	{ "Trousers", kPart15_1, 19 },
	{ "Part 3", kPart15_2, 27 },
	{ "Shoes", kPart15_3, 16 },
	{ "Skin", kPart15_4, 23 },
};
const Part kParts16[] = {
	{ "Hair", kPart16_0, 6 },
	{ "Collar", kPart16_1, 24 },
	{ "Trousers", kPart16_2, 40 },
	{ "Cape", kPart16_3, 26 },
	{ "Skin", kPart16_4, 30 },
};
const Part kParts17[] = {
	{ "Hair", kPart17_0, 6 },
	{ "Skin", kPart17_1, 12 },
	{ "Part 3", kPart17_2, 5 },
	{ "Part 4", kPart17_3, 5 },
	{ "Belt", kPart17_4, 42 },
};
const Part kParts18[] = {
	{ "Part 1", kPart18_0, 9 },
	{ "Hilt", kPart18_1, 22 },
	{ "Slacks", kPart18_2, 10 },
	{ "Gloves", kPart18_3, 10 },
	{ "Skin", kPart18_4, 26 },
};
const Part kParts19[] = {
	{ "Hair", kPart19_0, 6 },
	{ "Shield", kPart19_1, 17 },
	{ "Slacks", kPart19_2, 5 },
	{ "Part 4", kPart19_3, 15 },
	{ "Skin", kPart19_4, 46 },
};
const Part kParts20[] = {
	{ "Part 1", kPart20_0, 7 },
	{ "Gloves", kPart20_1, 22 },
	{ "Drawers", kPart20_2, 15 },
	{ "Glasses", kPart20_3, 43 },
	{ "Skin", kPart20_4, 20 },
};
const Part kParts21[] = {
	{ "Hair", kPart21_0, 7 },
	{ "Gauntlet", kPart21_1, 29 },
	{ "Trousers", kPart21_2, 9 },
	{ "Skin 1", kPart21_3, 17 },
	{ "Skin 2", kPart21_4, 27 },
};
const Part kParts22[] = {
	{ "Hair", kPart22_0, 6 },
	{ "Gloves", kPart22_1, 27 },
	{ "Shoes", kPart22_2, 15 },
	{ "Gun", kPart22_3, 20 },
	{ "Skin", kPart22_4, 23 },
};
const Part kParts23[] = {
	{ "Hair", kPart23_0, 11 },
	{ "Part 2", kPart23_1, 5 },
	{ "Belt", kPart23_2, 5 },
	{ "Metal", kPart23_3, 9 },
	{ "Eyes", kPart23_4, 13 },
};
const Part kParts24[] = {
	{ "Hair", kPart24_0, 6 },
	{ "Jacket", kPart24_1, 10 },
	{ "Socks", kPart24_2, 5 },
	{ "Part 4", kPart24_3, 28 },
	{ "Skin", kPart24_4, 50 },
};
const Part kParts25[] = {
	{ "Hair", kPart25_0, 6 },
	{ "Shirt", kPart25_1, 10 },
	{ "Trousers", kPart25_2, 5 },
	{ "Part 4", kPart25_3, 5 },
	{ "Skin", kPart25_4, 34 },
};
const Part kParts26[] = {
	{ "Hair", kPart26_0, 5 },
	{ "Inner", kPart26_1, 33 },
	{ "Leggings", kPart26_2, 10 },
	{ "Part 4", kPart26_3, 8 },
	{ "Skin", kPart26_4, 28 },
};

const CharaParts kCharaParts[] = {
	{ 0, kParts00, 5 },
	{ 1, kParts01, 5 },
	{ 2, kParts02, 6 },
	{ 3, kParts03, 5 },
	{ 4, kParts04, 5 },
	{ 5, kParts05, 5 },
	{ 6, kParts06, 5 },
	{ 7, kParts07, 5 },
	{ 8, kParts08, 5 },
	{ 9, kParts09, 5 },
	{ 10, kParts10, 5 },
	{ 11, kParts11, 5 },
	{ 12, kParts12, 5 },
	{ 13, kParts13, 5 },
	{ 14, kParts14, 5 },
	{ 15, kParts15, 5 },
	{ 16, kParts16, 5 },
	{ 17, kParts17, 5 },
	{ 18, kParts18, 5 },
	{ 19, kParts19, 5 },
	{ 20, kParts20, 5 },
	{ 21, kParts21, 5 },
	{ 22, kParts22, 5 },
	{ 23, kParts23, 5 },
	{ 24, kParts24, 5 },
	{ 25, kParts25, 5 },
	{ 26, kParts26, 5 },
};

const char* Find(const Named* table, size_t count, unsigned value)
{
	for (size_t i = 0; i < count; ++i)
	{
		if (table[i].value == value)
			return table[i].name;
	}

	return "";
}

const CharaParts* FindParts(int chara)
{
	for (size_t i = 0; i < sizeof(kCharaParts) / sizeof(kCharaParts[0]); ++i)
	{
		if (kCharaParts[i].chara == chara)
			return &kCharaParts[i];
	}

	return nullptr;
}

}

const char* GameTables::CommandName(uint32_t command)
{
	return Find(kCommands, sizeof(kCommands) / sizeof(kCommands[0]), command);
}

const char* GameTables::PatternName(uint16_t pattern)
{
	return Find(kPatterns, sizeof(kPatterns) / sizeof(kPatterns[0]), pattern);
}

int GameTables::GetMoveCodeBitCount()
{
	return static_cast<int>(sizeof(kMoveCode) / sizeof(kMoveCode[0]));
}

bool GameTables::GetMoveCodeBit(int index, uint32_t& outMask, const char*& outName)
{
	if (index < 0 || index >= GetMoveCodeBitCount())
		return false;

	outMask = kMoveCode[index].value;
	outName = kMoveCode[index].name;
	return true;
}

const char* GameTables::PaletteName(int chara, int palette)
{
	if (chara < 0 || chara >= kPaletteCharaCount || palette < 0 ||
		palette >= kPaletteNameCount)
	{
		return "";
	}

	return kPaletteNames[chara][palette];
}

int GameTables::GetPaletteNameCount()
{
	return kPaletteNameCount;
}

int GameTables::GetPartCount(int chara)
{
	const CharaParts* const found = FindParts(chara);
	return found == nullptr ? 0 : found->count;
}

bool GameTables::GetPart(int chara, int index, const char*& outName,
	const unsigned char*& outEntries, int& outCount)
{
	const CharaParts* const found = FindParts(chara);
	if (found == nullptr || index < 0 || index >= found->count)
		return false;

	outName = found->parts[index].name;
	outEntries = found->parts[index].entries;
	outCount = found->parts[index].count;
	return true;
}
