#include "Game/PartColourTable.h"

// Generated by tools/extract_part_colours.py from the game's own .pat files.
// Do not edit by hand.

namespace {

struct Row
{
	unsigned char entry;
	unsigned short parts;
};

const Row kRows000[] = {
	{ 251, 114 },
	{ 252, 6 },
	{ 253, 3 },
};

const Row kRows001[] = {
	{ 2, 1 },
	{ 9, 1 },
	{ 48, 2 },
	{ 49, 1 },
	{ 81, 1 },
	{ 82, 1 },
	{ 89, 1 },
	{ 98, 1 },
	{ 165, 1 },
	{ 248, 1 },
	{ 249, 12 },
	{ 250, 22 },
	{ 251, 40 },
	{ 252, 1 },
	{ 253, 47 },
};

const Row kRows010[] = {
	{ 251, 63 },
	{ 252, 40 },
	{ 253, 60 },
	{ 254, 10 },
	{ 255, 21 },
};

const Row kRows011[] = {
	{ 183, 2 },
	{ 203, 27 },
	{ 204, 11 },
	{ 205, 11 },
	{ 206, 17 },
	{ 207, 17 },
};

const Row kRows012[] = {
	{ 251, 70 },
	{ 252, 45 },
	{ 253, 3 },
	{ 254, 18 },
};

const Row kRows013[] = {
	{ 251, 62 },
	{ 252, 16 },
	{ 253, 22 },
	{ 254, 14 },
};

const Row kRows014[] = {
	{ 85, 2 },
	{ 91, 4 },
	{ 172, 4 },
	{ 192, 1 },
	{ 251, 19 },
	{ 252, 42 },
	{ 253, 53 },
	{ 254, 16 },
	{ 255, 3 },
};

const Row kRows015[] = {
	{ 177, 13 },
	{ 178, 7 },
	{ 181, 7 },
	{ 182, 13 },
	{ 186, 21 },
	{ 202, 68 },
	{ 203, 64 },
	{ 204, 5 },
	{ 205, 34 },
	{ 206, 11 },
	{ 207, 19 },
	{ 208, 7 },
	{ 210, 2 },
	{ 221, 1 },
	{ 230, 4 },
	{ 232, 2 },
	{ 240, 9 },
};

const Row kRows016[] = {
	{ 208, 1 },
	{ 210, 1 },
	{ 218, 1 },
	{ 220, 1 },
	{ 227, 1 },
	{ 229, 3 },
	{ 230, 1 },
	{ 248, 32 },
	{ 249, 67 },
	{ 250, 123 },
	{ 251, 154 },
	{ 252, 31 },
	{ 253, 33 },
	{ 254, 47 },
	{ 255, 1 },
};

const Row kRows017[] = {
	{ 129, 2 },
	{ 130, 11 },
	{ 237, 15 },
	{ 248, 27 },
	{ 249, 99 },
	{ 250, 89 },
	{ 251, 87 },
	{ 252, 83 },
	{ 253, 18 },
	{ 254, 1 },
};

const Row kRows018[] = {
	{ 46, 1 },
	{ 47, 3 },
	{ 225, 2 },
	{ 233, 22 },
	{ 234, 1 },
	{ 250, 65 },
	{ 251, 120 },
	{ 252, 5 },
	{ 253, 12 },
	{ 255, 19 },
};

const Row kRows019[] = {
	{ 1, 1 },
	{ 209, 4 },
	{ 214, 18 },
	{ 230, 46 },
	{ 250, 14 },
	{ 251, 8 },
	{ 252, 37 },
	{ 253, 126 },
	{ 254, 36 },
};

const Row kRows002[] = {
	{ 251, 17 },
	{ 252, 9 },
	{ 253, 6 },
	{ 254, 9 },
	{ 255, 6 },
};

const Row kRows020[] = {
	{ 24, 5 },
	{ 208, 1 },
	{ 210, 2 },
	{ 232, 348 },
	{ 233, 83 },
	{ 234, 19 },
	{ 237, 63 },
	{ 238, 13 },
};

const Row kRows021[] = {
	{ 192, 10 },
	{ 193, 2 },
	{ 194, 1 },
	{ 200, 1 },
	{ 201, 10 },
	{ 248, 30 },
	{ 249, 23 },
	{ 250, 32 },
	{ 251, 10 },
	{ 252, 10 },
	{ 253, 3 },
};

const Row kRows022[] = {
	{ 205, 1 },
	{ 248, 8 },
	{ 249, 27 },
	{ 250, 6 },
	{ 251, 80 },
	{ 252, 46 },
	{ 253, 29 },
	{ 254, 77 },
	{ 255, 38 },
};

const Row kRows023[] = {
	{ 54, 2 },
	{ 252, 349 },
};

const Row kRows024[] = {
	{ 250, 17 },
	{ 251, 84 },
	{ 252, 9 },
	{ 253, 5 },
	{ 254, 17 },
	{ 255, 15 },
};

const Row kRows025[] = {
	{ 1, 4 },
	{ 2, 6 },
	{ 80, 2 },
	{ 81, 6 },
	{ 195, 2 },
	{ 211, 2 },
	{ 246, 16 },
	{ 247, 6 },
	{ 248, 290 },
	{ 249, 33 },
	{ 250, 6 },
	{ 252, 2 },
	{ 253, 3 },
	{ 254, 6 },
};

const Row kRows026[] = {
	{ 248, 6 },
	{ 249, 204 },
	{ 250, 187 },
	{ 251, 2 },
	{ 252, 54 },
	{ 253, 4 },
	{ 254, 11 },
};

const Row kRows003[] = {
	{ 251, 166 },
	{ 252, 7 },
	{ 254, 36 },
};

const Row kRows004[] = {
	{ 187, 34 },
	{ 188, 6 },
	{ 189, 30 },
	{ 190, 5 },
	{ 191, 10 },
};

const Row kRows005[] = {
	{ 251, 41 },
	{ 252, 10 },
	{ 253, 17 },
	{ 254, 21 },
	{ 255, 40 },
};

const Row kRows006[] = {
	{ 224, 62 },
	{ 225, 12 },
	{ 226, 5 },
	{ 227, 24 },
	{ 228, 4 },
	{ 254, 1 },
};

const Row kRows007[] = {
	{ 235, 47 },
	{ 236, 11 },
	{ 237, 57 },
	{ 238, 32 },
	{ 239, 8 },
};

const Row kRows008[] = {
	{ 251, 31 },
	{ 252, 11 },
	{ 253, 18 },
	{ 254, 23 },
	{ 255, 73 },
};

const Row kRows009[] = {
	{ 160, 10 },
	{ 161, 2 },
	{ 162, 1 },
	{ 169, 9 },
	{ 170, 1 },
	{ 171, 13 },
	{ 203, 55 },
	{ 204, 1 },
	{ 205, 12 },
	{ 206, 11 },
	{ 208, 2 },
	{ 234, 1 },
};

struct Chara
{
	int number;
	const Row* rows;
	int count;
};

const Chara kCharas[] = {
	{ 0, kRows000, 3 },
	{ 1, kRows001, 15 },
	{ 10, kRows010, 5 },
	{ 11, kRows011, 6 },
	{ 12, kRows012, 4 },
	{ 13, kRows013, 4 },
	{ 14, kRows014, 9 },
	{ 15, kRows015, 17 },
	{ 16, kRows016, 15 },
	{ 17, kRows017, 10 },
	{ 18, kRows018, 10 },
	{ 19, kRows019, 9 },
	{ 2, kRows002, 5 },
	{ 20, kRows020, 8 },
	{ 21, kRows021, 11 },
	{ 22, kRows022, 9 },
	{ 23, kRows023, 2 },
	{ 24, kRows024, 6 },
	{ 25, kRows025, 14 },
	{ 26, kRows026, 7 },
	{ 3, kRows003, 3 },
	{ 4, kRows004, 5 },
	{ 5, kRows005, 5 },
	{ 6, kRows006, 6 },
	{ 7, kRows007, 5 },
	{ 8, kRows008, 5 },
	{ 9, kRows009, 12 },
};

const Chara* FindChara(int chara)
{
	for (const Chara& entry : kCharas)
	{
		if (entry.number == chara)
			return &entry;
	}

	return nullptr;
}

}

bool PartColourTable::IsPartEntry(int chara, int entry)
{
	const Chara* const found = FindChara(chara);
	if (found == nullptr)
		return false;

	for (int i = 0; i < found->count; ++i)
	{
		if (found->rows[i].entry == entry)
			return true;
	}

	return false;
}

int PartColourTable::GetPartCount(int chara, int entry)
{
	const Chara* const found = FindChara(chara);
	if (found == nullptr)
		return 0;

	for (int i = 0; i < found->count; ++i)
	{
		if (found->rows[i].entry == entry)
			return found->rows[i].parts;
	}

	return 0;
}
